stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:latest
      shellScript: |-
        mkdir -p /root/.m2 && mv setting.xml /root/.m2
        cat /root/.m2/setting.xml
        mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: default/jenkins-test:v1
      pushRemote: true
      registry: 192.168.157.65:8888
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
