stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:latest
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: default/jenkins-test:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.157.65:8888
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
