stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:latest
      shellScript: |-
        mkdir -p /root/.m2 && mv setting.xml /root/.m2
        mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xuyaohui/jenkins-test:v1
      pushRemote: true
      registry: 192.168.157.65:8888/default/xuyaohui/jenkins-test
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 60
