apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-demo
        track: stable
    spec:
      containers:
        - name: demo
          image: 192.168.157.65:8888/dafault/jenkins-test:v1
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-svc
spec:
  type: NodePort
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      nodePort: 31689
      port: 8082
      targetPort: 8082
